drop table member if exists cascade;
create table member (
    member_id bigint generated by default as identity,
    name varchar(10) not null,
    id varchar(20) not null,
    password varchar(100) not null,
    primary key (member_id)
);